### ISSUE TITLE
[Feature Request] Add more syntax sugar to Permission class

### ISSUE THREAD

**Issue by frol** [hustlzp/permission#1]
_/offtop First of all, I would like to say thank you! I really like your powerful yet simple and lightweight module! I have been bumping my head against Flask-Principal for days, but it is unnecessary too complex and I don't like the look of the code, and still I couldn't find the right way of using it (it seems that even the author has troubles with it...)._

Here is my suggestion as to the subject:
Add "with" statement syntax work, for example:

``` python
class AdminRolePermission(Permission):
    # ...

# ...
with AdminRolePermission():
    # do something
```

It should be quite straightforward to implement and looks way better than

``` python
permission = AdminRolePermissions()
if not permission.check():
    permission.deny()
else:
    # do something
```

**Comment by hustlzp** [comment]
I have to say I'm also been bumping my head against Flask-Principal for a long time, I really hate its complex!

Your suggestion is good, I will start to work on it in my spare time.

Thanks!

**Comment by frol** [comment]
Please, review PR #2
